### ISSUE TITLE
刷新头部

### ISSUE THREAD

**Issue by yanglilizhang** [NikiLee2016/react-native-bounce-flatlist#2]
感谢作者的组件,请问在andorid端怎么这个刷新头部一直浮在其他界面上,感觉我布局没问题啊
![_20190123195753](https://user-images.githubusercontent.com/42633135/51605216-5aebfe80-1f49-11e9-9512-2472a5a08287.png)

**Comment by NikiLee2016** [comment]
这应该是rn新版本导致的bug, 我的项目中也出现了. 我修复好了通知你

**Comment by NikiLee2016** [comment]
@shitouzhang 你的头部view, style设置zIndex: 10, 试试

**Comment by yanglilizhang** [comment]
多谢回复我试试
